In [1]:
import torch
torch.__version__

'2.9.1+cu128'

In [2]:
# Scalar
scalar = torch.tensor(7)
print(repr(scalar))
scalar.ndim, scalar.item()

tensor(7)


(0, 7)

In [3]:
# Vector
vector = torch.tensor([7,7])
print(repr(vector))
vector.ndim, vector.shape

tensor([7, 7])


(1, torch.Size([2]))

In [4]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
print(repr(MATRIX))
MATRIX.ndim, MATRIX.shape

tensor([[ 7,  8],
        [ 9, 10]])


(2, torch.Size([2, 2]))

In [5]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(repr(TENSOR))
TENSOR.ndim, TENSOR.shape

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


(3, torch.Size([1, 3, 3]))

In [6]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.4868, 0.0671, 0.6886, 0.3021],
         [0.5324, 0.5494, 0.2392, 0.8194],
         [0.6288, 0.4468, 0.6413, 0.6126]]),
 torch.float32)

In [7]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [8]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [9]:
ones = torch.ones(size=(3,4))
ones, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 2)

In [10]:
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
float_32_tensor = torch.tensor([3.,4.,5.], dtype=None, device=None, requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [13]:
torch.tensor([3.,6.,9.], dtype=torch.float16).dtype

torch.float16

In [14]:
some_tensor = torch.rand(3,4)
some_tensor.device

device(type='cpu')

In [15]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [16]:
tensor * 10

tensor([10, 20, 30])

In [17]:
tensor - 10

tensor([-9, -8, -7])

In [18]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [19]:
tensor * tensor

tensor([1, 4, 9])

In [20]:
tensor @ tensor.unsqueeze(0).mT

tensor([14])

In [21]:
torch.matmul(tensor, tensor)

tensor(14)

In [22]:
tensor @ tensor

tensor(14)

In [23]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 152 μs, sys: 185 μs, total: 337 μs
Wall time: 265 μs


tensor(14)

In [24]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 363 μs, sys: 442 μs, total: 805 μs
Wall time: 503 μs


tensor(14)

In [25]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,8],[9,10],[11,12]])

In [26]:
tensor_A @ tensor_B.T, tensor_B @ tensor_A.T, torch.mm(tensor_A, tensor_B.T), torch.mul(tensor_A, tensor_B), tensor_A * tensor_B

(tensor([[ 23,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]),
 tensor([[ 23,  53,  83],
         [ 29,  67, 105],
         [ 35,  81, 127]]),
 tensor([[ 23,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]),
 tensor([[ 7, 16],
         [27, 40],
         [55, 72]]),
 tensor([[ 7, 16],
         [27, 40],
         [55, 72]]))

In [27]:
linear = torch.nn.Linear(in_features=2, out_features=6)
linear(tensor_A.float())

tensor([[ 0.5400, -1.7784, -0.3749,  0.2100,  1.4345, -0.2325],
        [ 2.0428, -4.1935,  0.2122, -0.1769,  2.2858, -0.6884],
        [ 3.5456, -6.6086,  0.7993, -0.5638,  3.1371, -1.1444]],
       grad_fn=<AddmmBackward0>)

In [28]:
x = torch.arange(00, 100, 10)
x, x.min(), x.max(), x.sum(), x.to(torch.float16).mean(),torch.argmax(x), x.argmin()

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 tensor(0),
 tensor(90),
 tensor(450),
 tensor(45., dtype=torch.float16),
 tensor(9),
 tensor(0))

In [29]:
tensor_A, tensor_A.reshape((2,3)), tensor_A.flatten(), tensor_A.flatten().reshape(6,1), tensor_A.view(6,1)

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([1, 2, 3, 4, 5, 6]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6]]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6]]))

In [30]:
torch.stack([tensor_A, tensor_B]), torch.stack([tensor_A, tensor_B], dim=1), torch.stack([tensor_A, tensor_B], dim=2)

(tensor([[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],
 
         [[ 7,  8],
          [ 9, 10],
          [11, 12]]]),
 tensor([[[ 1,  2],
          [ 7,  8]],
 
         [[ 3,  4],
          [ 9, 10]],
 
         [[ 5,  6],
          [11, 12]]]),
 tensor([[[ 1,  7],
          [ 2,  8]],
 
         [[ 3,  9],
          [ 4, 10]],
 
         [[ 5, 11],
          [ 6, 12]]]))

In [31]:
torch.stack([tensor_A.squeeze(), tensor_B.squeeze()]), torch.concat([tensor_A, tensor_B]), torch.concat([tensor_A, tensor_B], dim=1)

(tensor([[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],
 
         [[ 7,  8],
          [ 9, 10],
          [11, 12]]]),
 tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12]]),
 tensor([[ 1,  2,  7,  8],
         [ 3,  4,  9, 10],
         [ 5,  6, 11, 12]]))

In [32]:
random_image_size_tensor.permute(2,0,1).shape

torch.Size([3, 224, 224])

In [33]:
x = torch.arange(1,10).view(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [34]:
x[:,0], x[:,:,1], x[:, 1, 1], x[0,0,:]

(tensor([[1, 2, 3]]), tensor([[2, 5, 8]]), tensor([5]), tensor([1, 2, 3]))

In [35]:
x.numpy(), torch.tensor(x.numpy())

(array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [36]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
A = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
B = torch.rand(3,4)
A == B

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [37]:
device = 'mps' if torch.backends.mps.is_available() else 'cpu'
device

'cpu'

In [38]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [39]:
torch.cuda.device_count()

1

In [40]:
torch.backends.cudnn.m.is_available()

True

In [41]:
x_gpu = x.to(device, dtype=torch.int8)
x, x.numpy().dtype, x_gpu, x_gpu.cpu().numpy()

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 dtype('int64'),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]], device='cuda:0', dtype=torch.int8),
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=int8))